### PR TITLE
Texture encoding

### PR DESCRIPTION
**Pull request by SinsofSloth**
- Tested everything but these:
  - (Low priority) HiLo8 encoding is not implemented, but I don't think the game uses it given sources say it's deprecated.
  - A4 and L4 not implemented, as idk how to handle a bit vector due to a bit4 data type not being native; open for suggestions on how to handle that to encode
  - (High priority) ETC1 & ETC1A4 might look later; just wanted to push this
- Probably might start arc repacking later.
- Renamed "texture_decoder" to "texture"; might create sub modules in this module (ie. decoder and encoder)

PS: Spica doesn't include encoding-- only how to swizzle

### CODE REVIEW

**Comment by thane98** [comment]
I won't be able to integrate it into Paragon yet since I'm currently working on other features, but I think we can look into adding texture replacement once the new module system's finished.

I wouldn't worry about HiLo8. Unless we hit textures that use that format, there's no need to implement it.

For L4 and A4, I don't remember if the games use these. If they do, messing around with bitwise ops might be the simplest approach. Otherwise, you might look at a crate like [bitvec](https://docs.rs/bitvec/0.19.3/bitvec/index.html).

I wouldn't worry about arc repacking either. I don't have it in a repo yet, but I've got an arc implementation that's built on top of [bin_archive.rs](https://github.com/thane98/mila/blob/master/src/bin_archive.rs). We can add repacking to that later - it'll be easier than trying to handle all of the pointer and text data manually.

**Comment by SinsofSloth** [comment]
No worries. I dealt w/ the bits w/o bitvecs, so no new dependencies were needed. For ETC1 and ETC1A4, it's done via ffi, as you can imagine how long the compression code is minus all the memory allocation. It seems a bit slower than I would like, but I'll see if I can speed it up.

**Comment by SinsofSloth** [comment]
This is ready for merge whenever you feel like it. I had to remove "include" from gitignore since I had an include folder for c++ headers. I hope that's okay, since I saw no mention of "include" in your repo.

**Comment by thane98** [comment]
Yeah, changing the gitignore is fine.

So this introduces a dependency on a C/C++ compiler, right? Do you need to have Visual Studio, gcc, or clang installed to do builds now?

If so, we probably need to add that as a requirement in the README.

I'm not big on introducing C/C++ on top of what's already there, but I think it's fine for now. I can look into moving this to Rust at some point, but this is fine for now.

**Comment by SinsofSloth** [comment]
Yes, so a C/C++ compiler is needed if you need to compile the C/C++ library, as stated [here](https://github.com/alexcrichton/cc-rs#c-support). We could mitigate the need to build the library everytime by putting thecompiled library into the directory. That would just require adding ``links= etc1_encoder" into cargo.toml and just commenting out the build script. After all, the C++ code is not going to be changed in the near future, unless adding options for compression quality. Sorry about throwing C++ into mix btw.

**Comment by thane98** [comment]
Precompiled sounds like a decent option. I know a couple people who will still need to build manually, but that shouldn't be a big deal if they just need to go through the install.

No need to apologize either - this will be a big feature once it's merged and integrated!

**Comment by SinsofSloth** [comment]
Awesome! I added the pre-compiled library under ``src/cpp/etc1_encoder/lib/release`` and edited the README and build script.

**Pull request closed without merging**
