### PR TITLE
Add Completer Support to Conversation 

### PR DESCRIPTION
**Pull request by SinsofSloth**
Currently displays a popup list of only commands. Do you think it would be good to add a list of other data (i.e. character names and emotions)?

### CODE REVIEW

**Comment by thane98** [comment]
This looks great and should definitely be an addition with the new/rewritten dialogue system. I can merge what you have here, but it'll have to be moved into the rewritten version once that's ready. I'll try to a branch up with the rewrite soon so that this isn't an issue with every PR.

Completion for emotions may be possible since that's static data. Character names would also be possible, but it would require some extra work since the names can change if the user adds/removes entries from the FaceData module.

**Comment by SinsofSloth** [comment]
Personally, Qt's completer is rather lacking. For future reference: [Qscintilla](https://qscintilla.com/#home) could be used instead, once things stabilize. Only PyQt supports it, but you could just write a wrapper for an implementation of the UI and call it. It had good features like [so](https://qscintilla.com/#autocompletion/call_tips), which is definitely looks far more appealing than Qt's autocompleter.

**Comment by thane98** [comment]
Yeah, I've used QScintilla before - it's a good option if you're on PyQt.

I'd like to stay on PySide2 for now since that's where the Qt Company's resources are for Python. That also leaves the option of upgrading to PySide6 in the future.

**Comment by SinsofSloth** [comment]
Alrighty. As for emotions and names, it would be rather bothersome if the popup showed up when writing text. Can I propose a change to emotions, and possibly names, to be prefixed with a special character that way it won't be troublesome for the enduser? Possibly 2 different prefixes besides `$` so it won't bloat the popup menu with misc items.

**Comment by thane98** [comment]
I'm not sure about adding prefixes to emotions and names for completion alone. I'd rather not add new symbols for the user to learn / manage if they aren't important for parsing. We can experiment with it if the other options aren't practical though.

The rewritten dialogue system has some changes that may make this easier. For example, all commands with parameters include parentheses now, so there's no need to manage spaces vs parentheses.

It's been a while since I've used QCompleter, but the pattern for when to suggest character names shouldn't be _that_ complicated since only two commands use them. So if you get "$SetSpeaker(" then character names should be suggested. Emotions could be done similarly, but I see how that can get more difficult.

**Pull request merged**
