### PR TITLE
BCH parsing

### PR DESCRIPTION
**Pull request by SinsofSloth**
- FE:IF Arc unpacking: Awaiting testing
  - Might add Awakening unpacking
- BCH: WIP; awaiting testing
- ETC1 decoding: oh god oh god oh god. 

Reminder to self: add license of FEAT and Ohana/spica

### CODE REVIEW

**Comment by thane98** [comment]
I don't see anything wrong with your syntax. Your code for arc unpacking looks fine in general. Only one thing stood out:

`pub fn unpack(archive: &[u8]) -> Result<File>`

Shouldn't this return a `Result<Vec<File>>`? It already reads multiple files, so it should probably return all of them.

**Comment by SinsofSloth** [comment]
🤔 Currently function PICA_command_reader is the last component of bch processing, besides the decompression and testing, because 
- I'm not sure how to create an array/list that I can just append an element to the end of it. Refer to: https://github.com/gdkchan/Ohana3DS-Rebirth/blob/76e3976b202ec117d47cbc3b476fc4d540a678c0/Ohana3DS%20Rebirth/Ohana/Models/PICA200/PICACommandReader.cs#L41 (Line 41-62)
- How to deal with global var? I was reading online and been seeing that it was like unsafe to do so.

**Comment by SinsofSloth** [comment]
Gonna need to download this crate https://docs.rs/piet/0.0.6/piet/enum.Color.html, but I wouldn't know how to with my terminal, unless you know how to represent color as a data type https://github.com/gdkchan/SPICA/blob/42c4181e198b0fd34f0a567345ee7e75b54cb58b/SPICA/PICA/Converters/TextureCompression.cs#L122

**Comment by SinsofSloth** [comment]
ETC1 decompression kinda in limbo atm, as I'm missing some basic functions, but is done being copied. Might be bug hunting it for days lol with all those bitwise operators.

**Comment by thane98** [comment]
That's a lot of progress - thanks for all of the hard work!

Adding crates in Rust is easy. Just add a line to the Cargo.toml file under `[dependencies]`. For example, for Piet you would add the line `piet = "0.1.0"`. You can use [crates.io](https://crates.io/) to find the correct version number to use.

Paragon already uses PyO3 to call Rust code from Python. The library also supports calling Python from Rust, so that could be used in a pinch. It might be easier to expose a couple of Rust functions to handle unpacking / parsing and deal with the rest through Python. bin_archive.rs does this by using pyclass + pymethods so that it can return a BinArchive struct to Python, but you can also expose functions on their own (lib.rs does this).

I'll start looking into what we could do for an image viewer. Qt might have a way to do that so we can avoid pulling in a C library.

**Pull request closed without merging**
